SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID 
    in (SELECT ITEM_ID
    FROM ITEM_TREE t
    WHERE t.PARENT_ITEM_ID 
        in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE'))
ORDER BY ITEM_ID desc
